# Generated by Django 4.2.7 on 2024-03-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='chat_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
