# Generated by Django 4.2.7 on 2024-03-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseManagement', '0002_student_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
