# Generated by Django 4.2.7 on 2024-03-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseManagement', '0003_alter_student_student_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='previously_interacted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
